version: '2'
services:
  driver:
    scale: 1
    start_on_create: true
  zeppelin:
    scale: 1
    start_on_create: true
  worker:
    scale: 3
    start_on_create: true
  master:
    scale: 1
    start_on_create: true
