version: '2'
volumes:
  minio-scheduler-setting:
    driver: local
    per_container: true
  minio-data-0:
    driver: local
    per_container: true
services:
  rancher-cattle-metadata:
    image: webcenter/rancher-cattle-metadata:1.0.1
    network_mode: none
    volumes:
    - minio-scheduler-setting:/opt/scheduler
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: test=true
  minio-server:
    image: webcenter/alpine-minio:2017-03-16_4
    environment:
      CONFD_BACKEND: env
      CONFD_NODES: ''
      CONFD_PREFIX_KEY: /minio
      MINIO_CONFIG_minio.access.key: rancher-minio
      MINIO_CONFIG_minio.secret.key: beeforchicken
      MINIO_DISKS_0: disk0
    volumes:
    - minio-scheduler-setting:/opt/scheduler
    - minio-data-0:/data/disk0
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: rancher-cattle-metadata
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: test=true
