version: '2'
services:
  rancher-cattle-metadata:
    retain_ip: true
    scale: 1
    start_on_create: true
  minio-server:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
